/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiResponseWrapperData } from './ApiResponseWrapperData';
import {
    ApiResponseWrapperDataFromJSON,
    ApiResponseWrapperDataFromJSONTyped,
    ApiResponseWrapperDataToJSON,
    ApiResponseWrapperDataToJSONTyped,
} from './ApiResponseWrapperData';

/**
 * 
 * @export
 * @interface ApiResponseWrapper
 */
export interface ApiResponseWrapper {
    /**
     * HTTP status code
     * @type {number}
     * @memberof ApiResponseWrapper
     */
    status: number;
    /**
     * Description of the response
     * @type {string}
     * @memberof ApiResponseWrapper
     */
    description: string;
    /**
     * 
     * @type {ApiResponseWrapperData}
     * @memberof ApiResponseWrapper
     */
    data: ApiResponseWrapperData;
}

/**
 * Check if a given object implements the ApiResponseWrapper interface.
 */
export function instanceOfApiResponseWrapper(value: object): value is ApiResponseWrapper {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApiResponseWrapperFromJSON(json: any): ApiResponseWrapper {
    return ApiResponseWrapperFromJSONTyped(json, false);
}

export function ApiResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'description': json['description'],
        'data': ApiResponseWrapperDataFromJSON(json['data']),
    };
}

export function ApiResponseWrapperToJSON(json: any): ApiResponseWrapper {
    return ApiResponseWrapperToJSONTyped(json, false);
}

export function ApiResponseWrapperToJSONTyped(value?: ApiResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'description': value['description'],
        'data': ApiResponseWrapperDataToJSON(value['data']),
    };
}

