/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePlatformScreeningSubmissionResponseDto
 */
export interface CreatePlatformScreeningSubmissionResponseDto {
    /**
     * Screening Submission Id
     * @type {string}
     * @memberof CreatePlatformScreeningSubmissionResponseDto
     */
    screeningSubmissionId: string;
}

/**
 * Check if a given object implements the CreatePlatformScreeningSubmissionResponseDto interface.
 */
export function instanceOfCreatePlatformScreeningSubmissionResponseDto(value: object): value is CreatePlatformScreeningSubmissionResponseDto {
    if (!('screeningSubmissionId' in value) || value['screeningSubmissionId'] === undefined) return false;
    return true;
}

export function CreatePlatformScreeningSubmissionResponseDtoFromJSON(json: any): CreatePlatformScreeningSubmissionResponseDto {
    return CreatePlatformScreeningSubmissionResponseDtoFromJSONTyped(json, false);
}

export function CreatePlatformScreeningSubmissionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlatformScreeningSubmissionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningSubmissionId': json['screeningSubmissionId'],
    };
}

export function CreatePlatformScreeningSubmissionResponseDtoToJSON(json: any): CreatePlatformScreeningSubmissionResponseDto {
    return CreatePlatformScreeningSubmissionResponseDtoToJSONTyped(json, false);
}

export function CreatePlatformScreeningSubmissionResponseDtoToJSONTyped(value?: CreatePlatformScreeningSubmissionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningSubmissionId': value['screeningSubmissionId'],
    };
}

