/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePlatformOrganisationBillingStripeSessionResponseDto
 */
export interface CreatePlatformOrganisationBillingStripeSessionResponseDto {
    /**
     * Message
     * @type {string}
     * @memberof CreatePlatformOrganisationBillingStripeSessionResponseDto
     */
    message: string;
    /**
     * Stripe Payment Session ID
     * @type {string}
     * @memberof CreatePlatformOrganisationBillingStripeSessionResponseDto
     */
    stripePaymentSessionId: string;
}

/**
 * Check if a given object implements the CreatePlatformOrganisationBillingStripeSessionResponseDto interface.
 */
export function instanceOfCreatePlatformOrganisationBillingStripeSessionResponseDto(value: object): value is CreatePlatformOrganisationBillingStripeSessionResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('stripePaymentSessionId' in value) || value['stripePaymentSessionId'] === undefined) return false;
    return true;
}

export function CreatePlatformOrganisationBillingStripeSessionResponseDtoFromJSON(json: any): CreatePlatformOrganisationBillingStripeSessionResponseDto {
    return CreatePlatformOrganisationBillingStripeSessionResponseDtoFromJSONTyped(json, false);
}

export function CreatePlatformOrganisationBillingStripeSessionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlatformOrganisationBillingStripeSessionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'stripePaymentSessionId': json['stripePaymentSessionId'],
    };
}

export function CreatePlatformOrganisationBillingStripeSessionResponseDtoToJSON(json: any): CreatePlatformOrganisationBillingStripeSessionResponseDto {
    return CreatePlatformOrganisationBillingStripeSessionResponseDtoToJSONTyped(json, false);
}

export function CreatePlatformOrganisationBillingStripeSessionResponseDtoToJSONTyped(value?: CreatePlatformOrganisationBillingStripeSessionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'stripePaymentSessionId': value['stripePaymentSessionId'],
    };
}

