/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePlatformScreeningSubmissionStreamingRoomTokenDto
 */
export interface CreatePlatformScreeningSubmissionStreamingRoomTokenDto {
    /**
     * Screening Job ID
     * @type {string}
     * @memberof CreatePlatformScreeningSubmissionStreamingRoomTokenDto
     */
    screeningJobId: string;
    /**
     * Screening Submission ID
     * @type {string}
     * @memberof CreatePlatformScreeningSubmissionStreamingRoomTokenDto
     */
    screeningSubmissionId: string;
    /**
     * Current Date Time in Epoch
     * @type {number}
     * @memberof CreatePlatformScreeningSubmissionStreamingRoomTokenDto
     */
    currDateTimeEpoch: number;
}

/**
 * Check if a given object implements the CreatePlatformScreeningSubmissionStreamingRoomTokenDto interface.
 */
export function instanceOfCreatePlatformScreeningSubmissionStreamingRoomTokenDto(value: object): value is CreatePlatformScreeningSubmissionStreamingRoomTokenDto {
    if (!('screeningJobId' in value) || value['screeningJobId'] === undefined) return false;
    if (!('screeningSubmissionId' in value) || value['screeningSubmissionId'] === undefined) return false;
    if (!('currDateTimeEpoch' in value) || value['currDateTimeEpoch'] === undefined) return false;
    return true;
}

export function CreatePlatformScreeningSubmissionStreamingRoomTokenDtoFromJSON(json: any): CreatePlatformScreeningSubmissionStreamingRoomTokenDto {
    return CreatePlatformScreeningSubmissionStreamingRoomTokenDtoFromJSONTyped(json, false);
}

export function CreatePlatformScreeningSubmissionStreamingRoomTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlatformScreeningSubmissionStreamingRoomTokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningJobId': json['screeningJobId'],
        'screeningSubmissionId': json['screeningSubmissionId'],
        'currDateTimeEpoch': json['currDateTimeEpoch'],
    };
}

export function CreatePlatformScreeningSubmissionStreamingRoomTokenDtoToJSON(json: any): CreatePlatformScreeningSubmissionStreamingRoomTokenDto {
    return CreatePlatformScreeningSubmissionStreamingRoomTokenDtoToJSONTyped(json, false);
}

export function CreatePlatformScreeningSubmissionStreamingRoomTokenDtoToJSONTyped(value?: CreatePlatformScreeningSubmissionStreamingRoomTokenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningJobId': value['screeningJobId'],
        'screeningSubmissionId': value['screeningSubmissionId'],
        'currDateTimeEpoch': value['currDateTimeEpoch'],
    };
}

