/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateScreeningTemplateDto
 */
export interface CreateScreeningTemplateDto {
    /**
     * Template Title
     * @type {string}
     * @memberof CreateScreeningTemplateDto
     */
    title: string;
    /**
     * Template Description
     * @type {string}
     * @memberof CreateScreeningTemplateDto
     */
    description: string;
    /**
     * Template Prompt
     * @type {string}
     * @memberof CreateScreeningTemplateDto
     */
    prompt: string;
    /**
     * Is the Template Streaming (Real Time)
     * @type {boolean}
     * @memberof CreateScreeningTemplateDto
     */
    isStreaming: boolean;
    /**
     * Template Questions
     * @type {Array<string>}
     * @memberof CreateScreeningTemplateDto
     */
    questions: Array<string>;
    /**
     * Created At
     * @type {string}
     * @memberof CreateScreeningTemplateDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the CreateScreeningTemplateDto interface.
 */
export function instanceOfCreateScreeningTemplateDto(value: object): value is CreateScreeningTemplateDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('isStreaming' in value) || value['isStreaming'] === undefined) return false;
    if (!('questions' in value) || value['questions'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateScreeningTemplateDtoFromJSON(json: any): CreateScreeningTemplateDto {
    return CreateScreeningTemplateDtoFromJSONTyped(json, false);
}

export function CreateScreeningTemplateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScreeningTemplateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'prompt': json['prompt'],
        'isStreaming': json['isStreaming'],
        'questions': json['questions'],
        'createdAt': json['createdAt'],
    };
}

export function CreateScreeningTemplateDtoToJSON(json: any): CreateScreeningTemplateDto {
    return CreateScreeningTemplateDtoToJSONTyped(json, false);
}

export function CreateScreeningTemplateDtoToJSONTyped(value?: CreateScreeningTemplateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'prompt': value['prompt'],
        'isStreaming': value['isStreaming'],
        'questions': value['questions'],
        'createdAt': value['createdAt'],
    };
}

