/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateScreeningTemplateQuestionsDto
 */
export interface GenerateScreeningTemplateQuestionsDto {
    /**
     * Task Title
     * @type {string}
     * @memberof GenerateScreeningTemplateQuestionsDto
     */
    jobTitle: string;
}

/**
 * Check if a given object implements the GenerateScreeningTemplateQuestionsDto interface.
 */
export function instanceOfGenerateScreeningTemplateQuestionsDto(value: object): value is GenerateScreeningTemplateQuestionsDto {
    if (!('jobTitle' in value) || value['jobTitle'] === undefined) return false;
    return true;
}

export function GenerateScreeningTemplateQuestionsDtoFromJSON(json: any): GenerateScreeningTemplateQuestionsDto {
    return GenerateScreeningTemplateQuestionsDtoFromJSONTyped(json, false);
}

export function GenerateScreeningTemplateQuestionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateScreeningTemplateQuestionsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jobTitle': json['jobTitle'],
    };
}

export function GenerateScreeningTemplateQuestionsDtoToJSON(json: any): GenerateScreeningTemplateQuestionsDto {
    return GenerateScreeningTemplateQuestionsDtoToJSONTyped(json, false);
}

export function GenerateScreeningTemplateQuestionsDtoToJSONTyped(value?: GenerateScreeningTemplateQuestionsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobTitle': value['jobTitle'],
    };
}

