/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAllOrganisationMemberStatusOfOrgListResponseDto
 */
export interface GetAllOrganisationMemberStatusOfOrgListResponseDto {
    /**
     * Accpeted Members Object List
     * @type {Array<string>}
     * @memberof GetAllOrganisationMemberStatusOfOrgListResponseDto
     */
    acceptedMembers: Array<string>;
    /**
     * Sent Members Object List
     * @type {Array<string>}
     * @memberof GetAllOrganisationMemberStatusOfOrgListResponseDto
     */
    sentMembers: Array<string>;
    /**
     * Super Admin
     * @type {object}
     * @memberof GetAllOrganisationMemberStatusOfOrgListResponseDto
     */
    superAdmin: object;
}

/**
 * Check if a given object implements the GetAllOrganisationMemberStatusOfOrgListResponseDto interface.
 */
export function instanceOfGetAllOrganisationMemberStatusOfOrgListResponseDto(value: object): value is GetAllOrganisationMemberStatusOfOrgListResponseDto {
    if (!('acceptedMembers' in value) || value['acceptedMembers'] === undefined) return false;
    if (!('sentMembers' in value) || value['sentMembers'] === undefined) return false;
    if (!('superAdmin' in value) || value['superAdmin'] === undefined) return false;
    return true;
}

export function GetAllOrganisationMemberStatusOfOrgListResponseDtoFromJSON(json: any): GetAllOrganisationMemberStatusOfOrgListResponseDto {
    return GetAllOrganisationMemberStatusOfOrgListResponseDtoFromJSONTyped(json, false);
}

export function GetAllOrganisationMemberStatusOfOrgListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllOrganisationMemberStatusOfOrgListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'acceptedMembers': json['acceptedMembers'],
        'sentMembers': json['sentMembers'],
        'superAdmin': json['superAdmin'],
    };
}

export function GetAllOrganisationMemberStatusOfOrgListResponseDtoToJSON(json: any): GetAllOrganisationMemberStatusOfOrgListResponseDto {
    return GetAllOrganisationMemberStatusOfOrgListResponseDtoToJSONTyped(json, false);
}

export function GetAllOrganisationMemberStatusOfOrgListResponseDtoToJSONTyped(value?: GetAllOrganisationMemberStatusOfOrgListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acceptedMembers': value['acceptedMembers'],
        'sentMembers': value['sentMembers'],
        'superAdmin': value['superAdmin'],
    };
}

