/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateScreeningTemplateDto } from './CreateScreeningTemplateDto';
import {
    CreateScreeningTemplateDtoFromJSON,
    CreateScreeningTemplateDtoFromJSONTyped,
    CreateScreeningTemplateDtoToJSON,
    CreateScreeningTemplateDtoToJSONTyped,
} from './CreateScreeningTemplateDto';

/**
 * 
 * @export
 * @interface GetAllPlatformScreeningTemplatesOfOrgResponseDto
 */
export interface GetAllPlatformScreeningTemplatesOfOrgResponseDto {
    /**
     * Screening Templates
     * @type {Array<CreateScreeningTemplateDto>}
     * @memberof GetAllPlatformScreeningTemplatesOfOrgResponseDto
     */
    screeningTemplates: Array<CreateScreeningTemplateDto>;
}

/**
 * Check if a given object implements the GetAllPlatformScreeningTemplatesOfOrgResponseDto interface.
 */
export function instanceOfGetAllPlatformScreeningTemplatesOfOrgResponseDto(value: object): value is GetAllPlatformScreeningTemplatesOfOrgResponseDto {
    if (!('screeningTemplates' in value) || value['screeningTemplates'] === undefined) return false;
    return true;
}

export function GetAllPlatformScreeningTemplatesOfOrgResponseDtoFromJSON(json: any): GetAllPlatformScreeningTemplatesOfOrgResponseDto {
    return GetAllPlatformScreeningTemplatesOfOrgResponseDtoFromJSONTyped(json, false);
}

export function GetAllPlatformScreeningTemplatesOfOrgResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllPlatformScreeningTemplatesOfOrgResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningTemplates': ((json['screeningTemplates'] as Array<any>).map(CreateScreeningTemplateDtoFromJSON)),
    };
}

export function GetAllPlatformScreeningTemplatesOfOrgResponseDtoToJSON(json: any): GetAllPlatformScreeningTemplatesOfOrgResponseDto {
    return GetAllPlatformScreeningTemplatesOfOrgResponseDtoToJSONTyped(json, false);
}

export function GetAllPlatformScreeningTemplatesOfOrgResponseDtoToJSONTyped(value?: GetAllPlatformScreeningTemplatesOfOrgResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningTemplates': ((value['screeningTemplates'] as Array<any>).map(CreateScreeningTemplateDtoToJSON)),
    };
}

