/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrganisationMemberStatusResponseDto
 */
export interface GetOrganisationMemberStatusResponseDto {
    /**
     * Organisation ID
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    orgId: string;
    /**
     * Organisation Alias
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    orgAlias: string;
    /**
     * Platform User ID
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    platformUserId: string;
    /**
     * Email of the user
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    email: string;
    /**
     * First name of the user
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    firstName: string;
    /**
     * Last name of the user
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    lastName: string;
    /**
     * Profile Picture URL of the user
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    dpUrl: string;
    /**
     * Status of the user
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    status: string;
    /**
     * Time of user creation in ISO Date Time String Format
     * @type {string}
     * @memberof GetOrganisationMemberStatusResponseDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the GetOrganisationMemberStatusResponseDto interface.
 */
export function instanceOfGetOrganisationMemberStatusResponseDto(value: object): value is GetOrganisationMemberStatusResponseDto {
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('orgAlias' in value) || value['orgAlias'] === undefined) return false;
    if (!('platformUserId' in value) || value['platformUserId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('dpUrl' in value) || value['dpUrl'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GetOrganisationMemberStatusResponseDtoFromJSON(json: any): GetOrganisationMemberStatusResponseDto {
    return GetOrganisationMemberStatusResponseDtoFromJSONTyped(json, false);
}

export function GetOrganisationMemberStatusResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganisationMemberStatusResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['orgId'],
        'orgAlias': json['orgAlias'],
        'platformUserId': json['platformUserId'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'dpUrl': json['dpUrl'],
        'status': json['status'],
        'createdAt': json['createdAt'],
    };
}

export function GetOrganisationMemberStatusResponseDtoToJSON(json: any): GetOrganisationMemberStatusResponseDto {
    return GetOrganisationMemberStatusResponseDtoToJSONTyped(json, false);
}

export function GetOrganisationMemberStatusResponseDtoToJSONTyped(value?: GetOrganisationMemberStatusResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgId': value['orgId'],
        'orgAlias': value['orgAlias'],
        'platformUserId': value['platformUserId'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'dpUrl': value['dpUrl'],
        'status': value['status'],
        'createdAt': value['createdAt'],
    };
}

