/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrganisationBillingViaOrgIdResponseDto
 */
export interface GetOrganisationBillingViaOrgIdResponseDto {
    /**
     * Organisation ID
     * @type {string}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    orgId: string;
    /**
     * Organisation Alias
     * @type {string}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    orgAlias: string;
    /**
     * Organisation Super Admin ID
     * @type {string}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    orgSuperAdminId: string;
    /**
     * Balance
     * @type {number}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    balance: number;
    /**
     * Currency
     * @type {string}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    currency: string;
    /**
     * Usage
     * @type {Array<string>}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    usage: Array<string>;
    /**
     * Transactions
     * @type {Array<string>}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    transactions: Array<string>;
    /**
     * Last Updated
     * @type {string}
     * @memberof GetOrganisationBillingViaOrgIdResponseDto
     */
    lastUpdated: string;
}

/**
 * Check if a given object implements the GetOrganisationBillingViaOrgIdResponseDto interface.
 */
export function instanceOfGetOrganisationBillingViaOrgIdResponseDto(value: object): value is GetOrganisationBillingViaOrgIdResponseDto {
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('orgAlias' in value) || value['orgAlias'] === undefined) return false;
    if (!('orgSuperAdminId' in value) || value['orgSuperAdminId'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function GetOrganisationBillingViaOrgIdResponseDtoFromJSON(json: any): GetOrganisationBillingViaOrgIdResponseDto {
    return GetOrganisationBillingViaOrgIdResponseDtoFromJSONTyped(json, false);
}

export function GetOrganisationBillingViaOrgIdResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganisationBillingViaOrgIdResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['orgId'],
        'orgAlias': json['orgAlias'],
        'orgSuperAdminId': json['orgSuperAdminId'],
        'balance': json['balance'],
        'currency': json['currency'],
        'usage': json['usage'],
        'transactions': json['transactions'],
        'lastUpdated': json['lastUpdated'],
    };
}

export function GetOrganisationBillingViaOrgIdResponseDtoToJSON(json: any): GetOrganisationBillingViaOrgIdResponseDto {
    return GetOrganisationBillingViaOrgIdResponseDtoToJSONTyped(json, false);
}

export function GetOrganisationBillingViaOrgIdResponseDtoToJSONTyped(value?: GetOrganisationBillingViaOrgIdResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orgId': value['orgId'],
        'orgAlias': value['orgAlias'],
        'orgSuperAdminId': value['orgSuperAdminId'],
        'balance': value['balance'],
        'currency': value['currency'],
        'usage': value['usage'],
        'transactions': value['transactions'],
        'lastUpdated': value['lastUpdated'],
    };
}

