/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPlatformOrganisationApiKeyResponseDto
 */
export interface GetPlatformOrganisationApiKeyResponseDto {
    /**
     * Api Key
     * @type {string}
     * @memberof GetPlatformOrganisationApiKeyResponseDto
     */
    apiKey: string;
    /**
     * Organisation Alias
     * @type {string}
     * @memberof GetPlatformOrganisationApiKeyResponseDto
     */
    organisationAlias: string;
    /**
     * Organisation Id
     * @type {string}
     * @memberof GetPlatformOrganisationApiKeyResponseDto
     */
    organisationId: string;
}

/**
 * Check if a given object implements the GetPlatformOrganisationApiKeyResponseDto interface.
 */
export function instanceOfGetPlatformOrganisationApiKeyResponseDto(value: object): value is GetPlatformOrganisationApiKeyResponseDto {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('organisationAlias' in value) || value['organisationAlias'] === undefined) return false;
    if (!('organisationId' in value) || value['organisationId'] === undefined) return false;
    return true;
}

export function GetPlatformOrganisationApiKeyResponseDtoFromJSON(json: any): GetPlatformOrganisationApiKeyResponseDto {
    return GetPlatformOrganisationApiKeyResponseDtoFromJSONTyped(json, false);
}

export function GetPlatformOrganisationApiKeyResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlatformOrganisationApiKeyResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'],
        'organisationAlias': json['organisationAlias'],
        'organisationId': json['organisationId'],
    };
}

export function GetPlatformOrganisationApiKeyResponseDtoToJSON(json: any): GetPlatformOrganisationApiKeyResponseDto {
    return GetPlatformOrganisationApiKeyResponseDtoToJSONTyped(json, false);
}

export function GetPlatformOrganisationApiKeyResponseDtoToJSONTyped(value?: GetPlatformOrganisationApiKeyResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKey': value['apiKey'],
        'organisationAlias': value['organisationAlias'],
        'organisationId': value['organisationId'],
    };
}

