/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformScreeningJobResponseDto } from './PlatformScreeningJobResponseDto';
import {
    PlatformScreeningJobResponseDtoFromJSON,
    PlatformScreeningJobResponseDtoFromJSONTyped,
    PlatformScreeningJobResponseDtoToJSON,
    PlatformScreeningJobResponseDtoToJSONTyped,
} from './PlatformScreeningJobResponseDto';

/**
 * 
 * @export
 * @interface PlatformScreeningJobListResponseDto
 */
export interface PlatformScreeningJobListResponseDto {
    /**
     * List of Screening Jobs
     * @type {Array<PlatformScreeningJobResponseDto>}
     * @memberof PlatformScreeningJobListResponseDto
     */
    screeningJobs: Array<PlatformScreeningJobResponseDto>;
}

/**
 * Check if a given object implements the PlatformScreeningJobListResponseDto interface.
 */
export function instanceOfPlatformScreeningJobListResponseDto(value: object): value is PlatformScreeningJobListResponseDto {
    if (!('screeningJobs' in value) || value['screeningJobs'] === undefined) return false;
    return true;
}

export function PlatformScreeningJobListResponseDtoFromJSON(json: any): PlatformScreeningJobListResponseDto {
    return PlatformScreeningJobListResponseDtoFromJSONTyped(json, false);
}

export function PlatformScreeningJobListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformScreeningJobListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningJobs': ((json['screeningJobs'] as Array<any>).map(PlatformScreeningJobResponseDtoFromJSON)),
    };
}

export function PlatformScreeningJobListResponseDtoToJSON(json: any): PlatformScreeningJobListResponseDto {
    return PlatformScreeningJobListResponseDtoToJSONTyped(json, false);
}

export function PlatformScreeningJobListResponseDtoToJSONTyped(value?: PlatformScreeningJobListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningJobs': ((value['screeningJobs'] as Array<any>).map(PlatformScreeningJobResponseDtoToJSON)),
    };
}

