/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformOrganisationsListResponseDto
 */
export interface PlatformOrganisationsListResponseDto {
    /**
     * List of Organisations
     * @type {Array<string>}
     * @memberof PlatformOrganisationsListResponseDto
     */
    organisations: Array<string>;
}

/**
 * Check if a given object implements the PlatformOrganisationsListResponseDto interface.
 */
export function instanceOfPlatformOrganisationsListResponseDto(value: object): value is PlatformOrganisationsListResponseDto {
    if (!('organisations' in value) || value['organisations'] === undefined) return false;
    return true;
}

export function PlatformOrganisationsListResponseDtoFromJSON(json: any): PlatformOrganisationsListResponseDto {
    return PlatformOrganisationsListResponseDtoFromJSONTyped(json, false);
}

export function PlatformOrganisationsListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformOrganisationsListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'organisations': json['organisations'],
    };
}

export function PlatformOrganisationsListResponseDtoToJSON(json: any): PlatformOrganisationsListResponseDto {
    return PlatformOrganisationsListResponseDtoToJSONTyped(json, false);
}

export function PlatformOrganisationsListResponseDtoToJSONTyped(value?: PlatformOrganisationsListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisations': value['organisations'],
    };
}

