/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformScreeningSubmissionResponseDto } from './PlatformScreeningSubmissionResponseDto';
import {
    PlatformScreeningSubmissionResponseDtoFromJSON,
    PlatformScreeningSubmissionResponseDtoFromJSONTyped,
    PlatformScreeningSubmissionResponseDtoToJSON,
    PlatformScreeningSubmissionResponseDtoToJSONTyped,
} from './PlatformScreeningSubmissionResponseDto';

/**
 * 
 * @export
 * @interface PlatformScreeningSubmissionListResponseDto
 */
export interface PlatformScreeningSubmissionListResponseDto {
    /**
     * Screening Submissions
     * @type {Array<PlatformScreeningSubmissionResponseDto>}
     * @memberof PlatformScreeningSubmissionListResponseDto
     */
    screeningSubmissions: Array<PlatformScreeningSubmissionResponseDto>;
}

/**
 * Check if a given object implements the PlatformScreeningSubmissionListResponseDto interface.
 */
export function instanceOfPlatformScreeningSubmissionListResponseDto(value: object): value is PlatformScreeningSubmissionListResponseDto {
    if (!('screeningSubmissions' in value) || value['screeningSubmissions'] === undefined) return false;
    return true;
}

export function PlatformScreeningSubmissionListResponseDtoFromJSON(json: any): PlatformScreeningSubmissionListResponseDto {
    return PlatformScreeningSubmissionListResponseDtoFromJSONTyped(json, false);
}

export function PlatformScreeningSubmissionListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformScreeningSubmissionListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningSubmissions': ((json['screeningSubmissions'] as Array<any>).map(PlatformScreeningSubmissionResponseDtoFromJSON)),
    };
}

export function PlatformScreeningSubmissionListResponseDtoToJSON(json: any): PlatformScreeningSubmissionListResponseDto {
    return PlatformScreeningSubmissionListResponseDtoToJSONTyped(json, false);
}

export function PlatformScreeningSubmissionListResponseDtoToJSONTyped(value?: PlatformScreeningSubmissionListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningSubmissions': ((value['screeningSubmissions'] as Array<any>).map(PlatformScreeningSubmissionResponseDtoToJSON)),
    };
}

