/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformScreeningSubmissionCreateStreamRoomResponseDto
 */
export interface PlatformScreeningSubmissionCreateStreamRoomResponseDto {
    /**
     * Token
     * @type {string}
     * @memberof PlatformScreeningSubmissionCreateStreamRoomResponseDto
     */
    accessToken: string;
    /**
     * Url
     * @type {string}
     * @memberof PlatformScreeningSubmissionCreateStreamRoomResponseDto
     */
    url: string;
}

/**
 * Check if a given object implements the PlatformScreeningSubmissionCreateStreamRoomResponseDto interface.
 */
export function instanceOfPlatformScreeningSubmissionCreateStreamRoomResponseDto(value: object): value is PlatformScreeningSubmissionCreateStreamRoomResponseDto {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PlatformScreeningSubmissionCreateStreamRoomResponseDtoFromJSON(json: any): PlatformScreeningSubmissionCreateStreamRoomResponseDto {
    return PlatformScreeningSubmissionCreateStreamRoomResponseDtoFromJSONTyped(json, false);
}

export function PlatformScreeningSubmissionCreateStreamRoomResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformScreeningSubmissionCreateStreamRoomResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'url': json['url'],
    };
}

export function PlatformScreeningSubmissionCreateStreamRoomResponseDtoToJSON(json: any): PlatformScreeningSubmissionCreateStreamRoomResponseDto {
    return PlatformScreeningSubmissionCreateStreamRoomResponseDtoToJSONTyped(json, false);
}

export function PlatformScreeningSubmissionCreateStreamRoomResponseDtoToJSONTyped(value?: PlatformScreeningSubmissionCreateStreamRoomResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'url': value['url'],
    };
}

