/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformScreeningJobResponseDto
 */
export interface PlatformScreeningJobResponseDto {
    /**
     * Screening Job Id
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    screeningJobId: string;
    /**
     * Organisation ID
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    orgId: string;
    /**
     * Organisation alias
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    orgAlias: string;
    /**
     * Screening Template ID
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    screeningTemplateId: string;
    /**
     * Screening Job Title
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    title: string;
    /**
     * Screening Job Active Status
     * @type {boolean}
     * @memberof PlatformScreeningJobResponseDto
     */
    jobActive: boolean;
    /**
     * Screening Job JD
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    jd: string;
    /**
     * Upvoted By
     * @type {Array<string>}
     * @memberof PlatformScreeningJobResponseDto
     */
    upvotes: Array<string>;
    /**
     * Creation date in ISO Date Time String
     * @type {string}
     * @memberof PlatformScreeningJobResponseDto
     */
    createdAt: string;
}

/**
 * Check if a given object implements the PlatformScreeningJobResponseDto interface.
 */
export function instanceOfPlatformScreeningJobResponseDto(value: object): value is PlatformScreeningJobResponseDto {
    if (!('screeningJobId' in value) || value['screeningJobId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('orgAlias' in value) || value['orgAlias'] === undefined) return false;
    if (!('screeningTemplateId' in value) || value['screeningTemplateId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('jobActive' in value) || value['jobActive'] === undefined) return false;
    if (!('jd' in value) || value['jd'] === undefined) return false;
    if (!('upvotes' in value) || value['upvotes'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PlatformScreeningJobResponseDtoFromJSON(json: any): PlatformScreeningJobResponseDto {
    return PlatformScreeningJobResponseDtoFromJSONTyped(json, false);
}

export function PlatformScreeningJobResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformScreeningJobResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningJobId': json['screeningJobId'],
        'orgId': json['orgId'],
        'orgAlias': json['orgAlias'],
        'screeningTemplateId': json['screeningTemplateId'],
        'title': json['title'],
        'jobActive': json['jobActive'],
        'jd': json['jd'],
        'upvotes': json['upvotes'],
        'createdAt': json['createdAt'],
    };
}

export function PlatformScreeningJobResponseDtoToJSON(json: any): PlatformScreeningJobResponseDto {
    return PlatformScreeningJobResponseDtoToJSONTyped(json, false);
}

export function PlatformScreeningJobResponseDtoToJSONTyped(value?: PlatformScreeningJobResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningJobId': value['screeningJobId'],
        'orgId': value['orgId'],
        'orgAlias': value['orgAlias'],
        'screeningTemplateId': value['screeningTemplateId'],
        'title': value['title'],
        'jobActive': value['jobActive'],
        'jd': value['jd'],
        'upvotes': value['upvotes'],
        'createdAt': value['createdAt'],
    };
}

