/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScreeningFormSubmissionQuestionDto
 */
export interface ScreeningFormSubmissionQuestionDto {
    /**
     * Index of the question
     * @type {number}
     * @memberof ScreeningFormSubmissionQuestionDto
     */
    index: number;
    /**
     * Agent Question
     * @type {string}
     * @memberof ScreeningFormSubmissionQuestionDto
     */
    agent: string;
    /**
     * Human Answer
     * @type {string}
     * @memberof ScreeningFormSubmissionQuestionDto
     */
    human: string;
    /**
     * Human Answer Audio URL
     * @type {string}
     * @memberof ScreeningFormSubmissionQuestionDto
     */
    humanAudioUrl: string;
    /**
     * Answer Type
     * @type {string}
     * @memberof ScreeningFormSubmissionQuestionDto
     */
    answerType: string;
    /**
     * Answers Given
     * @type {Array<string>}
     * @memberof ScreeningFormSubmissionQuestionDto
     */
    answersGiven: Array<string>;
}

/**
 * Check if a given object implements the ScreeningFormSubmissionQuestionDto interface.
 */
export function instanceOfScreeningFormSubmissionQuestionDto(value: object): value is ScreeningFormSubmissionQuestionDto {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('human' in value) || value['human'] === undefined) return false;
    if (!('humanAudioUrl' in value) || value['humanAudioUrl'] === undefined) return false;
    if (!('answerType' in value) || value['answerType'] === undefined) return false;
    if (!('answersGiven' in value) || value['answersGiven'] === undefined) return false;
    return true;
}

export function ScreeningFormSubmissionQuestionDtoFromJSON(json: any): ScreeningFormSubmissionQuestionDto {
    return ScreeningFormSubmissionQuestionDtoFromJSONTyped(json, false);
}

export function ScreeningFormSubmissionQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreeningFormSubmissionQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'agent': json['agent'],
        'human': json['human'],
        'humanAudioUrl': json['humanAudioUrl'],
        'answerType': json['answerType'],
        'answersGiven': json['answersGiven'],
    };
}

export function ScreeningFormSubmissionQuestionDtoToJSON(json: any): ScreeningFormSubmissionQuestionDto {
    return ScreeningFormSubmissionQuestionDtoToJSONTyped(json, false);
}

export function ScreeningFormSubmissionQuestionDtoToJSONTyped(value?: ScreeningFormSubmissionQuestionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'agent': value['agent'],
        'human': value['human'],
        'humanAudioUrl': value['humanAudioUrl'],
        'answerType': value['answerType'],
        'answersGiven': value['answersGiven'],
    };
}

