/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePlatformScreeningSubmissionsStatusDto
 */
export interface UpdatePlatformScreeningSubmissionsStatusDto {
    /**
     * Screening Submission IDs
     * @type {Array<string>}
     * @memberof UpdatePlatformScreeningSubmissionsStatusDto
     */
    screeningSubmissionIds: Array<string>;
    /**
     * Submission Status
     * @type {string}
     * @memberof UpdatePlatformScreeningSubmissionsStatusDto
     */
    status: string;
}

/**
 * Check if a given object implements the UpdatePlatformScreeningSubmissionsStatusDto interface.
 */
export function instanceOfUpdatePlatformScreeningSubmissionsStatusDto(value: object): value is UpdatePlatformScreeningSubmissionsStatusDto {
    if (!('screeningSubmissionIds' in value) || value['screeningSubmissionIds'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdatePlatformScreeningSubmissionsStatusDtoFromJSON(json: any): UpdatePlatformScreeningSubmissionsStatusDto {
    return UpdatePlatformScreeningSubmissionsStatusDtoFromJSONTyped(json, false);
}

export function UpdatePlatformScreeningSubmissionsStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlatformScreeningSubmissionsStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningSubmissionIds': json['screeningSubmissionIds'],
        'status': json['status'],
    };
}

export function UpdatePlatformScreeningSubmissionsStatusDtoToJSON(json: any): UpdatePlatformScreeningSubmissionsStatusDto {
    return UpdatePlatformScreeningSubmissionsStatusDtoToJSONTyped(json, false);
}

export function UpdatePlatformScreeningSubmissionsStatusDtoToJSONTyped(value?: UpdatePlatformScreeningSubmissionsStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningSubmissionIds': value['screeningSubmissionIds'],
        'status': value['status'],
    };
}

