/* tslint:disable */
/* eslint-disable */
/**
 * Screening AI API Docs
 * API Documentation for Screening AI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePlatformScreeningSubmissionChatDto
 */
export interface UpdatePlatformScreeningSubmissionChatDto {
    /**
     * Screening Submission ID
     * @type {string}
     * @memberof UpdatePlatformScreeningSubmissionChatDto
     */
    screeningSubmissionId: string;
    /**
     * Index of the question
     * @type {number}
     * @memberof UpdatePlatformScreeningSubmissionChatDto
     */
    index: number;
    /**
     * Agent Question
     * @type {string}
     * @memberof UpdatePlatformScreeningSubmissionChatDto
     */
    human: string;
    /**
     * Human Answer
     * @type {string}
     * @memberof UpdatePlatformScreeningSubmissionChatDto
     */
    humanAudioUrl: string;
    /**
     * Answer Type
     * @type {string}
     * @memberof UpdatePlatformScreeningSubmissionChatDto
     */
    answerType: string;
}

/**
 * Check if a given object implements the UpdatePlatformScreeningSubmissionChatDto interface.
 */
export function instanceOfUpdatePlatformScreeningSubmissionChatDto(value: object): value is UpdatePlatformScreeningSubmissionChatDto {
    if (!('screeningSubmissionId' in value) || value['screeningSubmissionId'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('human' in value) || value['human'] === undefined) return false;
    if (!('humanAudioUrl' in value) || value['humanAudioUrl'] === undefined) return false;
    if (!('answerType' in value) || value['answerType'] === undefined) return false;
    return true;
}

export function UpdatePlatformScreeningSubmissionChatDtoFromJSON(json: any): UpdatePlatformScreeningSubmissionChatDto {
    return UpdatePlatformScreeningSubmissionChatDtoFromJSONTyped(json, false);
}

export function UpdatePlatformScreeningSubmissionChatDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlatformScreeningSubmissionChatDto {
    if (json == null) {
        return json;
    }
    return {
        
        'screeningSubmissionId': json['screeningSubmissionId'],
        'index': json['index'],
        'human': json['human'],
        'humanAudioUrl': json['humanAudioUrl'],
        'answerType': json['answerType'],
    };
}

export function UpdatePlatformScreeningSubmissionChatDtoToJSON(json: any): UpdatePlatformScreeningSubmissionChatDto {
    return UpdatePlatformScreeningSubmissionChatDtoToJSONTyped(json, false);
}

export function UpdatePlatformScreeningSubmissionChatDtoToJSONTyped(value?: UpdatePlatformScreeningSubmissionChatDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screeningSubmissionId': value['screeningSubmissionId'],
        'index': value['index'],
        'human': value['human'],
        'humanAudioUrl': value['humanAudioUrl'],
        'answerType': value['answerType'],
    };
}

